
name: py4ds2e
channels:
  - conda-forge
dependencies:
  - jupyter
  - numpy
  - pandas
  - pip
  - python=3.10
  - pyyaml
  - scipy
  - statsmodels
  - yaml
  - pycodestyle
  - autopep8
  - pandas-datareader
  - pandasdmx
  - jupyter-book
  - pytest
  - pre-commit
  - jupyterlab
  - nbstripout
  - ghp-import
  - pip
  - black
  - black-jupyter
  - beautifulsoup4
  - pip:
    - skimpy
    - pyarrow
    - watermark
    - graphviz
    - openpyxl
    - sqlmodel
    - ibis-framework
    - lets-plot
    - polars
    - palmerpenguins
    - pandas-profiling
    - rich